### POST /coffees
POST http://localhost:3000/coffees
Content-Type: application/json

{}

### GET /coffees
GET http://localhost:3000/coffees

### GET /fibonacci
GET http://localhost:3000/fibonacci?n=5

### GET /payments-webhook
GET http://localhost:3000/payments-webhook

### GET /users
GET http://localhost:3000/users
x-tenant-id: 3
